services:
  web:
    build: .
    depends_on:
      - db
    command: gunicorn ridebot_passenger.wsgi:application --bind 0.0.0.0:8000
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ridebot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
