[project]
name = "passengerridebot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django-redis>=6.0.0",
    "django-stubs>=5.2.7",
    "gunicorn>=23.0.0",
    "pytelegrambotapi>=4.29.1",
    "whitenoise>=6.11.0",
]
